services:
  repomind:
    build: .
    container_name: repomind_app
    network_mode: host
    volumes:
      - /home/pratik/ML and DL projects/RepoMind:/workspace
      - /home/pratik:/home/pratik
    environment:
      OLLAMA_BASE_URL: http://127.0.0.1:11434
      OLLAMA_MODEL: phi3:mini
      BACKEND_URL: http://127.0.0.1:8000
    restart: unless-stopped
